---
title: "Cheat sheet"
output: html_document
---

Here are some of the commands and packages you'll be using. Remember that you can get help at any time by typing ?command (e.g. ?library) in the Console, or in RStudio's Help pane. Not all of these will be loaded directly - some are loaded as dependencies when you load other packages.

## Packages

* tidyverse
  - includes multiple packages covering plotting, data manipulation, file reading... (ggplot2, dplyr, tidyr, purrr)
* afex
  - a simple interface for running ANOVA 
* lme4
  - Linear Mixed-Effects modelling - includes generalized linear modelling (e.g. logistic regression)
* lsmeans
  - package for extracting, performing post-hoc tests.


## Commands

### tidyverse
* gather()
  - Used to bring multiple data columns into one single column
  - Any columns not excluded using -column_name will be brought into the new column
```
gather(your_df, new_factor_column, new_data_column, ...) #use -column_name to keep a column
```

* spread()
  - Used to spread data from one column into multiple columns

```
spread(your_df, existing_factor_column, existing_data_column, ...)
```

