---
title: "Loading multiple files"
output: html_notebook
---



```{r}
library(feather)
library(tidyverse)
```

```{r}
testf <- map_df(list.files('../data/','*.feather', full.names = TRUE),~read_feather(.x), .id = "Subject")
```



```{r}
testf <- testf %>%
  filter(time >= -100 & time <= 400) %>%
  separate(condition, into = c("light", "touch", "reported"), sep = "/") %>%
  gather(electrode, amplitude, Fp1:O2) 
```


```{r}
testf %>% 
  group_by(Subject, electrode, time) %>%
  summarise(amplitude = mean(amplitude)) %>%
  ggplot(aes(x = time, y = amplitude, colour = electrode)) +
  stat_summary(geom = "line")
```

```{r}
test3 <- test2 %>%
  filter(time >= 130 & time <= 160) %>%
  group_by(Subject,touch,light,epoch, electrode) %>%
  summarise(amplitude = mean(amplitude)) %>%
  ungroup()
```


```{r}
library(eegUtils)

test3 %>%
  group_by(Subject,electrode) %>%
  summarise(amplitude = mean(amplitude)) %>%
  topoplot()

topoplot(test3)


```

```{r}
library(lme4)
library(afex)
options(contrasts = c("contr.sum","contr.poly"))
test4 <- test3 %>%
  filter(electrode == "Oz" | electrode == "O1" | electrode == "O2") %>%
  group_by(Subject, light, touch, epoch) %>%
  summarise(amplitude = mean(amplitude)) %>%
  lmer(amplitude ~ light* touch + (0+ light:touch |Subject), data = .)
  

```

